[2024-10-03T21:10:04.146+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-03T21:10:04.186+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline.train_model scheduled__2024-10-03T21:05:00+00:00 [queued]>
[2024-10-03T21:10:04.200+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline.train_model scheduled__2024-10-03T21:05:00+00:00 [queued]>
[2024-10-03T21:10:04.201+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-03T21:10:04.208+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): train_model> on 2024-10-03 21:05:00+00:00
[2024-10-03T21:10:04.220+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=252) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-03T21:10:04.221+0000] {standard_task_runner.py:72} INFO - Started process 261 to run task
[2024-10-03T21:10:04.221+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'pipeline', 'train_model', 'scheduled__2024-10-03T21:05:00+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmp5gsw21h9']
[2024-10-03T21:10:04.223+0000] {standard_task_runner.py:105} INFO - Job 8: Subtask train_model
[2024-10-03T21:10:04.250+0000] {task_command.py:467} INFO - Running <TaskInstance: pipeline.train_model scheduled__2024-10-03T21:05:00+00:00 [running]> on host 3d575b970daa
[2024-10-03T21:10:04.289+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pipeline' AIRFLOW_CTX_TASK_ID='train_model' AIRFLOW_CTX_EXECUTION_DATE='2024-10-03T21:05:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-03T21:05:00+00:00'
[2024-10-03T21:10:04.291+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-03T21:10:04.363+0000] {logging_mixin.py:190} INFO - 287530613885451987
[2024-10-03T21:10:04.398+0000] {logging_mixin.py:190} WARNING - 2024/10/03 21:10:04 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2024-10-03T21:10:04.428+0000] {logging_mixin.py:190} INFO - ['Fuel_Type', 'Seller_Type', 'Transmission']
[2024-10-03T21:10:04.435+0000] {logging_mixin.py:190} INFO - Columns with missing values in data:  []
[2024-10-03T21:10:04.457+0000] {logging_mixin.py:190} INFO -          Year  Present_Price  ...  Transmission_Automatic  Transmission_Manual
0    0.785714       0.070777  ...                     0.0                  1.0
1    0.357143       0.001086  ...                     1.0                  0.0
2    0.142857       0.140903  ...                     0.0                  1.0
3    0.857143       0.088254  ...                     0.0                  1.0
4    0.857143       0.107469  ...                     0.0                  1.0
..        ...            ...  ...                     ...                  ...
235  0.857143       0.068606  ...                     0.0                  1.0
236  0.642857       0.000977  ...                     0.0                  1.0
237  0.857143       0.000651  ...                     0.0                  1.0
238  0.857143       0.020517  ...                     0.0                  1.0
239  0.285714       0.002931  ...                     0.0                  1.0

[240 rows x 11 columns]
[2024-10-03T21:10:09.000+0000] {logging_mixin.py:190} WARNING - 2024/10/03 21:10:08 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
[2024-10-03T21:10:09.178+0000] {logging_mixin.py:190} INFO - Mean squared error:  1.5818532786885244
[2024-10-03T21:10:09.185+0000] {logging_mixin.py:190} INFO - R2 score:  0.8706686914423317
[2024-10-03T21:10:09.210+0000] {logging_mixin.py:190} WARNING - 2024/10/03 21:10:09 INFO mlflow.tracking._tracking_service.client: üèÉ View run run 01 at: http://mlflow-server:5000/#/experiments/287530613885451987/runs/5a869b3540f34306a6b6a4ff138e111a.
[2024-10-03T21:10:09.218+0000] {logging_mixin.py:190} WARNING - 2024/10/03 21:10:09 INFO mlflow.tracking._tracking_service.client: üß™ View experiment at: http://mlflow-server:5000/#/experiments/287530613885451987.
[2024-10-03T21:10:09.226+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-10-03T21:10:09.275+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-03T21:10:09.276+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=pipeline, task_id=train_model, run_id=scheduled__2024-10-03T21:05:00+00:00, execution_date=20241003T210500, start_date=20241003T211004, end_date=20241003T211009
[2024-10-03T21:10:09.399+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-03T21:10:09.412+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-03T21:10:09.413+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
