[2024-10-02T21:14:44.659+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-02T21:14:44.865+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_preparation.read_data manual__2024-10-02T21:13:06.141106+00:00 [queued]>
[2024-10-02T21:14:44.939+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_preparation.read_data manual__2024-10-02T21:13:06.141106+00:00 [queued]>
[2024-10-02T21:14:44.961+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-02T21:14:45.115+0000] {taskinstance.py:2888} INFO - Executing <Task(_PythonDecoratedOperator): read_data> on 2024-10-02 21:13:06.141106+00:00
[2024-10-02T21:14:45.194+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=128) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-02T21:14:45.203+0000] {standard_task_runner.py:72} INFO - Started process 214 to run task
[2024-10-02T21:14:45.235+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'data_preparation', 'read_data', 'manual__2024-10-02T21:13:06.141106+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/prepare_data.py', '--cfg-path', '/tmp/tmph27xd6d6']
[2024-10-02T21:14:45.287+0000] {standard_task_runner.py:105} INFO - Job 6: Subtask read_data
[2024-10-02T21:14:45.625+0000] {task_command.py:467} INFO - Running <TaskInstance: data_preparation.read_data manual__2024-10-02T21:13:06.141106+00:00 [running]> on host 1039cb6c9818
[2024-10-02T21:14:46.017+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_preparation' AIRFLOW_CTX_TASK_ID='read_data' AIRFLOW_CTX_EXECUTION_DATE='2024-10-02T21:13:06.141106+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-02T21:13:06.141106+00:00'
[2024-10-02T21:14:46.051+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-02T21:14:46.381+0000] {python.py:240} INFO - Done. Returned value was:     Car_Name  Year  Selling_Price  ...  Seller_Type  Transmission Owner
0       ritz  2014           3.35  ...       Dealer        Manual     0
1        sx4  2013           4.75  ...       Dealer        Manual     0
2       ciaz  2017           7.25  ...       Dealer        Manual     0
3    wagon r  2011           2.85  ...       Dealer        Manual     0
4      swift  2014           4.60  ...       Dealer        Manual     0
..       ...   ...            ...  ...          ...           ...   ...
296     city  2016           9.50  ...       Dealer        Manual     0
297     brio  2015           4.00  ...       Dealer        Manual     0
298     city  2009           3.35  ...       Dealer        Manual     0
299     city  2017          11.50  ...       Dealer        Manual     0
300     brio  2016           5.30  ...       Dealer        Manual     0

[301 rows x 9 columns]
[2024-10-02T21:14:54.858+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-02T21:14:54.868+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=data_preparation, task_id=read_data, run_id=manual__2024-10-02T21:13:06.141106+00:00, execution_date=20241002T211306, start_date=20241002T211444, end_date=20241002T211454
[2024-10-02T21:14:55.121+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-02T21:14:55.385+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
[2024-10-02T21:14:55.472+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-02T21:14:55.491+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
